import { MatchedSetting } from './gpoParser';

/**
 * GPO → Intune GENERATOR.
 * Turns the matched/analyzed GPO settings into deployable Intune artifacts:
 *  - a Settings Catalog configuration policy (Graph beta JSON)
 *  - a PowerShell deployment script (Microsoft.Graph) that creates the policy
 *  - PowerShell remediation script stubs for "ScriptRequired" settings
 * The Tester then validates this JSON and (with SSO) can create it unassigned
 * in the target tenant via Graph to prove it imports cleanly.
 */

export interface GeneratedArtifacts {
  profileName: string;
  settingsCatalogJson: string;
  deployScript: string;
  remediationScripts: { name: string; script: string }[];
  manualSteps: string[];
  includedCount: number;
  scriptCount: number;
  manualCount: number;
}

// Map a confidence/category to a Settings Catalog setting definition id stub.
// Real definitionIds differ per setting; we emit a clearly-marked template the
// engineer completes/imports, plus the human-readable Intune path from the KB.
function toCatalogSetting(s: MatchedSetting) {
  const slug = s.setting.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '').slice(0, 60);
  return {
    '@odata.type': '#microsoft.graph.deviceManagementConfigurationSetting',
    settingInstance: {
      '@odata.type': '#microsoft.graph.deviceManagementConfigurationChoiceSettingInstance',
      settingDefinitionId: `device_vendor_msft_policy_config_${slug}`,
      // Source mapping kept as metadata so the engineer can verify/adjust:
      choiceSettingValue: {
        '@odata.type': '#microsoft.graph.deviceManagementConfigurationChoiceSettingValue',
        value: `${slug}_enabled`,
        children: [],
      },
    },
    _source: { gpo: s.name, scope: s.scope, intunePath: s.intunePath, confidence: s.confidence },
  };
}

export function generateArtifacts(settings: MatchedSetting[], profileName = 'WorkPilot - Migrated GPO'): GeneratedArtifacts {
  const supported = settings.filter((s) => s.support === 'Supported');
  const scriptReq = settings.filter((s) => s.support === 'ScriptRequired');
  const manual = settings.filter((s) => s.support === 'Manual' || s.support === 'Unsupported');

  const profile = {
    name: profileName,
    description: `Generated by WorkPilot from ${settings.length} GPO setting(s) on ${new Date().toISOString().slice(0, 10)}. Review setting definition IDs before assigning.`,
    platforms: 'windows10',
    technologies: 'mdm',
    roleScopeTagIds: ['0'],
    settings: supported.map(toCatalogSetting),
  };
  const settingsCatalogJson = JSON.stringify(profile, null, 2);

  const deployScript = `# ===== Deploy the generated Settings Catalog profile to Intune =====
# Requires: Microsoft.Graph module + delegated scope DeviceManagementConfiguration.ReadWrite.All
Connect-MgGraph -Scopes 'DeviceManagementConfiguration.ReadWrite.All'

$body = Get-Content '.\\${profileName.replace(/[^a-z0-9]+/gi, '-')}.json' -Raw
$created = Invoke-MgGraphRequest -Method POST \`
  -Uri 'https://graph.microsoft.com/beta/deviceManagement/configurationPolicies' \`
  -Body $body -ContentType 'application/json'
Write-Output "Created policy: $($created.id) — $($created.name)"

# The profile is created UNASSIGNED. Review it in Intune, then assign to a pilot group:
# New-MgBetaDeviceManagementConfigurationPolicyAssignment ...`;

  const remediationScripts = scriptReq.map((s) => ({
    name: `${s.name.replace(/[^a-z0-9]+/gi, '-').slice(0, 50)}.ps1`,
    script: `# Intune remediation/platform script generated from GPO: "${s.name}"
# Scope: ${s.scope} | Recommended target: ${s.intunePath}
# ${s.notes ?? ''}
# TODO: implement the equivalent of the GPO setting below. Deploy via
#   Intune > Devices > Scripts and remediations (run-once semantics differ
#   from logon scripts — test in a pilot ring first).

Write-Output "Applying ${s.name.replace(/"/g, "'")} ..."
# <-- add the registry / configuration commands here -->
`,
  }));

  const manualSteps = manual.map((s) =>
    `[${s.support}] ${s.name} (${s.scope}) → ${s.intunePath}${s.notes ? ` — ${s.notes}` : ''}`,
  );

  return {
    profileName,
    settingsCatalogJson,
    deployScript,
    remediationScripts,
    manualSteps,
    includedCount: supported.length,
    scriptCount: scriptReq.length,
    manualCount: manual.length,
  };
}

export interface ProfileValidation {
  ok: boolean;
  checks: { label: string; pass: boolean; detail: string }[];
}

/** Test/validate the generated profile JSON before any deployment. */
export function validateProfile(json: string): ProfileValidation {
  const checks: { label: string; pass: boolean; detail: string }[] = [];
  let parsed: { name?: string; platforms?: string; technologies?: string; settings?: unknown[] };
  try {
    parsed = JSON.parse(json);
    checks.push({ label: 'Valid JSON', pass: true, detail: 'Profile parses correctly.' });
  } catch (e) {
    checks.push({ label: 'Valid JSON', pass: false, detail: e instanceof Error ? e.message : String(e) });
    return { ok: false, checks };
  }
  checks.push({ label: 'Has profile name', pass: !!parsed.name, detail: parsed.name ? `"${parsed.name}"` : 'missing name' });
  checks.push({ label: 'Platform = windows10', pass: parsed.platforms === 'windows10', detail: parsed.platforms ?? 'missing' });
  checks.push({ label: 'Technology = mdm', pass: parsed.technologies === 'mdm', detail: parsed.technologies ?? 'missing' });
  const n = Array.isArray(parsed.settings) ? parsed.settings.length : 0;
  checks.push({ label: 'Contains settings', pass: n > 0, detail: `${n} setting(s)` });
  checks.push({ label: 'Each setting has a definition id', pass: Array.isArray(parsed.settings) && parsed.settings.every((s) => (s as { settingInstance?: { settingDefinitionId?: string } })?.settingInstance?.settingDefinitionId), detail: 'settingDefinitionId present on all' });
  return { ok: checks.every((c) => c.pass), checks };
}
