import { useMemo, useState } from 'react';
import { Wrench, Download, Wand2, Search } from 'lucide-react';
import { Badge, Button, Card, CodeBlock, CopyButton, Field, PageHeader, Section } from '../components/ui';
import { gpoCatalog, gpoCategories, GpoSettingDef } from '../data/gpoBuilderCatalog';
import { AIHelper } from '../components/AIHelper';

interface Selected {
  on: boolean;
  value: string | number;
}

export default function GpoBuilder() {
  const [gpoName, setGpoName] = useState('Contoso - Workstation Baseline');
  const [comment, setComment] = useState('Created with WorkPilot GPO Builder');
  const [sel, setSel] = useState<Record<string, Selected>>({});
  const [query, setQuery] = useState('');
  const [generated, setGenerated] = useState<string | null>(null);

  const toggle = (def: GpoSettingDef) => {
    setSel((prev) => {
      const cur = prev[def.id];
      if (cur?.on) { const { [def.id]: _, ...rest } = prev; return rest; }
      const value = def.input === 'toggle' ? (def.onValue ?? 1) : (def.default ?? (def.type === 'DWord' ? 0 : ''));
      return { ...prev, [def.id]: { on: true, value } };
    });
    setGenerated(null);
  };
  const setValue = (id: string, value: string | number) => {
    setSel((prev) => ({ ...prev, [id]: { on: true, value } }));
    setGenerated(null);
  };

  const chosen = gpoCatalog.filter((d) => sel[d.id]?.on);

  const filtered = useMemo(() => {
    const q = query.toLowerCase();
    return gpoCatalog.filter((d) => !q || d.label.toLowerCase().includes(q) || d.category.toLowerCase().includes(q) || d.valueName.toLowerCase().includes(q));
  }, [query]);

  const generate = () => {
    const lines: string[] = [
      '# ===== Custom GPO generated by WorkPilot =====',
      '# Run on a domain controller (or RSAT) with the GroupPolicy module.',
      'Import-Module GroupPolicy -ErrorAction Stop',
      '',
      `$gpoName = '${gpoName.replace(/'/g, "''")}'`,
      `$gpo = Get-GPO -Name $gpoName -ErrorAction SilentlyContinue`,
      `if (-not $gpo) { $gpo = New-GPO -Name $gpoName -Comment '${comment.replace(/'/g, "''")}' }`,
      '',
    ];
    for (const d of chosen) {
      const v = sel[d.id].value;
      const valArg = d.type === 'DWord' ? `-Type DWord -Value ${Number(v) || 0}` : `-Type ${d.type} -Value '${String(v).replace(/'/g, "''")}'`;
      lines.push(`# ${d.category} — ${d.label}`);
      lines.push(`Set-GPRegistryValue -Name $gpoName -Key 'HKEY_${d.hive === 'HKLM' ? 'LOCAL_MACHINE' : 'CURRENT_USER'}\\${d.key}' -ValueName '${d.valueName}' ${valArg} | Out-Null`);
      lines.push('');
    }
    lines.push('# Link the GPO to an OU (edit the target):');
    lines.push(`# New-GPLink -Name $gpoName -Target 'OU=Workstations,DC=contoso,DC=local' -LinkEnabled Yes`);
    lines.push('Write-Output "GPO \'$gpoName\' configured with ' + `${chosen.length}` + ' setting(s)."');
    setGenerated(lines.join('\n'));
  };

  const download = () => {
    if (!generated) return;
    const blob = new Blob([generated], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${gpoName.replace(/[^a-z0-9]+/gi, '-')}.ps1`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  return (
    <div>
      <PageHeader title="GPO Builder" subtitle="Pick the settings you want, fill in the values, and WorkPilot generates a ready-to-run PowerShell script that creates the custom GPO (New-GPO + Set-GPRegistryValue)." icon={<Wrench size={20} />} />

      <div className="grid gap-6 lg:grid-cols-[1fr_420px]">
        {/* Catalog picker */}
        <div className="space-y-4">
          <Card className="p-4">
            <div className="grid gap-3 sm:grid-cols-2">
              <Field label="GPO name" value={gpoName} onChange={setGpoName} />
              <Field label="Comment" value={comment} onChange={setComment} />
            </div>
          </Card>
          <Card className="p-4">
            <div className="relative mb-3">
              <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
              <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search settings…" className="w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 py-2 pl-9 pr-3 text-sm text-slate-800 dark:text-slate-100 focus:border-blue-500 focus:outline-none" />
            </div>
            {gpoCategories.map((cat) => {
              const items = filtered.filter((d) => d.category === cat);
              if (!items.length) return null;
              return (
                <div key={cat} className="mb-4">
                  <div className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-400">{cat}</div>
                  <div className="space-y-1.5">
                    {items.map((d) => {
                      const s = sel[d.id];
                      return (
                        <div key={d.id} className={`rounded-lg border p-2.5 ${s?.on ? 'border-blue-300 dark:border-blue-700 bg-blue-50/50 dark:bg-blue-900/10' : 'border-slate-200 dark:border-slate-700'}`}>
                          <label className="flex items-center gap-2.5 cursor-pointer">
                            <input type="checkbox" checked={!!s?.on} onChange={() => toggle(d)} className="h-4 w-4 rounded border-slate-300 text-blue-600" />
                            <span className="flex-1 text-sm text-slate-700 dark:text-slate-200">{d.label}</span>
                            <span className="text-[10px] text-slate-400">{d.hive}</span>
                          </label>
                          {s?.on && d.input !== 'toggle' && (
                            <div className="mt-2 pl-6">
                              {d.input === 'choice' ? (
                                <select value={s.value} onChange={(e) => setValue(d.id, d.type === 'DWord' ? Number(e.target.value) : e.target.value)} className="rounded border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 px-2 py-1 text-xs">
                                  {d.choices?.map((c) => <option key={c.value} value={c.value}>{c.label}</option>)}
                                </select>
                              ) : (
                                <input type={d.input === 'number' ? 'number' : 'text'} value={s.value} onChange={(e) => setValue(d.id, d.input === 'number' ? Number(e.target.value) : e.target.value)} className="w-full rounded border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-900 px-2 py-1 text-xs" />
                              )}
                              {d.help && <div className="mt-1 text-[10px] text-slate-400">{d.help}</div>}
                            </div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </Card>
        </div>

        {/* Output */}
        <div className="space-y-4 lg:sticky lg:top-20 lg:self-start">
          <Card className="p-5">
            <div className="mb-3 flex items-center justify-between">
              <span className="text-sm font-semibold text-slate-700 dark:text-slate-200">Selected: {chosen.length} setting(s)</span>
              <Button onClick={generate} disabled={!chosen.length}><Wand2 size={15} /> Generate GPO</Button>
            </div>
            {chosen.length > 0 && (
              <div className="flex flex-wrap gap-1.5">
                {chosen.map((d) => <Badge key={d.id} color="blue">{d.label}</Badge>)}
              </div>
            )}
            {!chosen.length && <p className="text-sm text-slate-400">Tick settings on the left, then Generate.</p>}
          </Card>

          {generated && (
            <Card className="p-5">
              <Section title="Generated GPO PowerShell" action={<div className="flex gap-2"><CopyButton text={generated} /><Button variant="secondary" onClick={download}><Download size={14} /> .ps1</Button></div>}>
                <CodeBlock code={generated} />
              </Section>
            </Card>
          )}

          {chosen.length > 0 && (
            <AIHelper context={`Building a GPO "${gpoName}" with: ${chosen.map((d) => d.label).join(', ')}.`} defaultPrompt="Review this GPO selection — any settings I should add for a secure workstation baseline, or conflicts to watch for?" />
          )}
        </div>
      </div>
    </div>
  );
}
